# Subprojects will refer to this for dependencies
[versions]
whisper-jni = "0.5.5"
json = "20250107"

[libraries]
whisperjni = { module = "io.github.freshsupasulley:whisper-jni", version.ref = "whisper-jni" }
json = { module = "org.json:json", version.ref = "json" }
