/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.freshsupasulley;

import java.io.FileInputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.concurrent.ExecutionException;

import javax.sound.sampled.UnsupportedAudioFileException;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import io.github.freshsupasulley.whisperjni.WhisperFullParams;
import io.github.freshsupasulley.whisperjni.WhisperJNI;

class JScribeTest {
	
	private static Path jfk = Path.of("src/main/resources/jfk.wav");
	private static Path testModel = Path.of("src/test/resources/base.en.bin");
	private static Logger logger = LoggerFactory.getLogger(JScribeTest.class);
	
	// @Disabled
	@BeforeAll
	@Test
	static void downloadModel() throws IOException, InterruptedException, ExecutionException
	{
		System.out.println("Test");
		assert JScribe.getModels().length != 0;
		
		// Don't download the model file if we already have it
		if(testModel.toFile().exists())
		{
			logger.info("Not downloading, already exists");
			return;
		}
		
		ModelDownloader downloader = JScribe.downloadModel("tiny", testModel, (hi, exception) ->
		{
		});
		
		while(!downloader.isDone())
		{
			logger.info("Bytes: {}", downloader.getBytesRead());
			
			Thread.sleep(500);
		}
	}
	
	// @Disabled
	@Test
	void testVulkan() throws Exception
	{
		if(!WhisperJNI.canUseVulkan())
			return;
		
		JScribe.Builder builder = new JScribe.Builder(testModel);//.warmUpModel();
		
		WhisperJNI.loadVulkan();
		
		JScribe scribe = builder.build();
		scribe.start();
		
		while(!scribe.isRunning())
		{
			System.out.println("Waiting to run");
			Thread.sleep(1000);
		}
		
		time(scribe);
	}
	
	@Test
	void testVAD() throws Exception
	{
		JScribe.Builder builder = new JScribe.Builder(testModel);
		builder.setLogger(logger);
		// Build params with VAD properties of client
		WhisperFullParams params = JScribe.createWhisperFullParams();
		
		Path tempFile = Files.createTempFile("temp_model", ".bin");
		WhisperJNI.exportVADModel(logger, tempFile);
		
		params.vad = true;
		params.vad_model_path = tempFile.toAbsolutePath().toString();
		params.vadParams.threshold = 0.5f;
		params.vadParams.min_speech_duration_ms = 200;
		params.vadParams.min_silence_duration_ms = 100;
		params.vadParams.max_speech_duration_s = 10;
		params.vadParams.speech_pad_ms = 200;
		params.vadParams.samples_overlap = 0.1f;
		builder.setWhisperFullParams(params);
//		builder.warmUpModel();
		
		JScribe scribe = builder.build();
		scribe.start();
		
		while(!scribe.isRunning())
		{
			System.out.println("Waiting to run");
			Thread.sleep(1000);
		}
		
		time(scribe);
	}
	
	private void time(JScribe scribe) throws UnsupportedAudioFileException, IOException, InterruptedException
	{
		System.out.println("Backlog : " + scribe.getTranscriptionBacklog());
		scribe.transcribe(JScribe.readWavToFloatSamples(new FileInputStream(jfk.toFile())));
		
		Transcriptions t = null;
		while((t = scribe.getTranscriptions()).isEmpty())
		{
			Thread.sleep(500);
		}
		
		System.out.println("Transcriptions: " + t.getTranscriptions().size());
		t.forEach(transcription ->
		{
			System.out.println("Took " + transcription.processingTime() + " --- " + transcription.text());
		});
		System.out.println();
	}
	
	@Disabled
	@Test
	void startStopTest() throws Exception
	{
		JScribe scribe = new JScribe.Builder(testModel).build();//.warmUpModel().build();
		
		long startTime = System.currentTimeMillis();
		long testDuration = 20000;
		
		System.out.println("Starting stability test");
		
		while(System.currentTimeMillis() - startTime < testDuration)
		{
			if(scribe.isInUse())
			{
				throw new IllegalStateException("Shouldn't be running!");
			}
			
			// Constantly start and stop
			scribe.start();
			// Thread.sleep(5000);
			scribe.stop();
		}
	}
}
