/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.nio.file.Paths;

import org.junit.jupiter.api.Test;

import com.supasulley.jscribe.JScribe;

class AppTest {
	
	/**
	 * This doesn't work when running from the IDE on Mac. Thanks Tim Apple!
	 */
	@Test
	void testModel()
	{
		JScribe scribe = new JScribe(Paths.get("src/test/resources/ggml-tiny.en.bin"));
		scribe.start("", 500, 1500);
		
		// Translate for a while
		long start = System.currentTimeMillis();
		
		while(System.currentTimeMillis() - start < 30000 && !scribe.isRunningAndNoAudio())
		{
			for(String buffer = null; !(buffer = scribe.getBuffer()).equals(""); System.out.println(buffer));
		}
	}
}
