/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.freshsupasulley;

import java.io.FileInputStream;
import java.io.IOException;
import java.nio.file.Path;
import java.util.concurrent.ExecutionException;

import javax.sound.sampled.UnsupportedAudioFileException;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import io.github.givimad.whisperjni.internal.LibraryUtils;

class JScribeTest {
	
	static Path testModel = Path.of("src/test/resources/base.en.bin");
	
	// @Disabled
	@BeforeAll
	@Test
	static void downloadModel() throws IOException, InterruptedException, ExecutionException
	{
		System.out.println("Test");
		assert JScribe.getModels().length != 0;
		
		// Don't download the model file if we already have it
		if(testModel.toFile().exists())
		{
			System.out.println("Not downloading, already exists");
			return;
		}
		
		ModelDownloader downloader = JScribe.downloadModel("tiny", testModel, (hi, exception) ->
		{
		});
		
		while(!downloader.isDone())
		{
			System.out.println(downloader.getBytesRead());
			
			Thread.sleep(500);
		}
	}
	
//	@Disabled
	@Test
	void testVulkan() throws Exception
	{
		if(!LibraryUtils.canUseVulkan()) return;
		
		JScribe.Builder builder = new JScribe.Builder(testModel).warmUpModel();
		
		// Load custom Vulkan natives manually because we have to
//		if(LibraryUtils.canUseVulkan())
//		{
//			builder.skipLoadingNatives();
//			
//			String vulkanPath = LibraryLoader.getVulkanDLL().toAbsolutePath().toString();
//			System.load(vulkanPath);
//			
////			Path tempDir = Path.of("src", "main", "resources", "win-amd64-vulkan");
////			System.load(tempDir.resolve("ggml.dll").toAbsolutePath().toString());
////			System.load(tempDir.resolve("whisper.dll").toAbsolutePath().toString());
////			System.load(tempDir.resolve("whisper-jni.dll").toAbsolutePath().toString());
//			
//			Path tempDir = Path.of("src", "main", "resources", "win-amd64-vulkan");
//			System.load(tempDir.resolve("ggml-base.dll").toAbsolutePath().toString());
//			System.load(tempDir.resolve("ggml-cpu.dll").toAbsolutePath().toString());
//			System.load(tempDir.resolve("ggml-vulkan.dll").toAbsolutePath().toString());
//			System.load(tempDir.resolve("ggml.dll").toAbsolutePath().toString());
//			System.load(tempDir.resolve("whisper.dll").toAbsolutePath().toString());
//			System.load(tempDir.resolve("whisper-jni.dll").toAbsolutePath().toString());
//		}
		LibraryUtils.loadVulkan();
		
		JScribe scribe = builder.build();
		scribe.start();
		
		while(!scribe.isRunning())
		{
			System.out.println("Waiting to run");
			Thread.sleep(1000);
		}
		
		time(scribe, "src/main/resources/jfk.wav");
	}
	
	private void time(JScribe scribe, String file) throws UnsupportedAudioFileException, IOException, InterruptedException
	{
		System.out.println("Backlog : " + scribe.getTranscriptionBacklog());
		scribe.transcribe(JScribe.readWavToFloatSamples(new FileInputStream(file)));
		
		Transcriptions t = null;
		while((t = scribe.getTranscriptions()).isEmpty())
		{
			Thread.sleep(500);
		}
		
		System.out.println("Transcriptions: " + t.getTranscriptions().size());
		t.forEach(transcription -> {
			System.out.println("Took " + transcription.processingTime() + " --- " + transcription.text());
		});
		System.out.println();
	}
	
	@Disabled
	@Test
	void startStopTest() throws Exception
	{
		JScribe scribe = new JScribe.Builder(testModel).warmUpModel().build();
		
		long startTime = System.currentTimeMillis();
		long testDuration = 20000;
		
		System.out.println("Starting stability test");
		
		while(System.currentTimeMillis() - startTime < testDuration)
		{
			if(scribe.isInUse())
			{
				throw new IllegalStateException("Shouldn't be running!");
			}
			
			// Constantly start and stop
			scribe.start();
//			Thread.sleep(5000);
			scribe.stop();
		}
	}
}
