name: Build and publish
on:
  release:
    types: [published]
  # might as well
  workflow_dispatch:
jobs:
  build-windows-x64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Build
        run: |
          ./gradlew :api:build
      - name: Publish test report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/**/*.xml'
      - name: Publish
        # Use special wrapper because jreleaser hates subprojects
        run: ./gradlew :api:jreleaserDeployWrapper
        env:
          JRELEASER_MAVENCENTRAL_STAGE: UPLOAD # Don't publish, just upload so I can review it
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.JRELEASER_MAVENCENTRAL_USERNAME }}
          JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.JRELEASER_MAVENCENTRAL_PASSWORD }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.JRELEASER_GPG_PASSPHRASE }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
